django/webapp/intro/urls.py
from django.urls import path
from .import views

app_name = 'intro'

urlpatterns = [
    path('', views.index, name = 'index'), #/intro
    path('masaru/', views.masaru, name = 'masaru'), #/masaru
    path('masaki/', views.masaki, name = 'masaki'), #/masaki
    path('yuka/', views.yuka, name = 'yuka'), #/yuka
    path('makiyama/', views.makiyama, name = 'makiyama'), #/makiyama
    path('add/', views.add, name = 'add'), 
    path('_list', views._list, name = '_list'), 
    path('update/<int:pk>/', views.update, name ='update'),
    path('delete/<int:pk>/', views.delete, name = 'delete'),
    path('detail/<int:pk>/', views.detail, name = 'detail'),
]

django/webapp/webapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('intro/', include('intro.urls')),
]

django/webapp/intro/models.py
from django.db import models
from django.utils import timezone

class Message(models.Model):
    title = models.CharField('宛先', max_length=500)
    text = models.TextField('本文')
    date = models.DateTimeField('日付', default = timezone.now)

django/webapp/intro/forms.py
from django import forms
from .models import Message

class MessageCreateForm(forms.ModelForm):

    class Meta:
        model = Message
        fields = '__all__' #('title','text','date')

django/webapp/intro/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import MessageCreateForm
from .models import Message

# Create your views here.
def index(request):
    return render(request, 'intro/home.html')

def masaru(request):
    return render(request, 'intro/masaru.html')

def masaki(request):
    return render(request, 'intro/masaki.html')

def yuka(request):
    return render(request, 'intro/yuka.html')

def makiyama(request):
    return render(request, 'intro/makiyama.html')

def _list(request):
    context ={
        'message_list':Message.objects.all()
    }
    return render(request, 'intro/message_list.html', context)
    
def add(request):

    form = MessageCreateForm(request.POST or None)

    if request.method =='POST' and form.is_valid():
        form.save()
        return redirect('intro:_list')
    context = {
        'form':form
    }
    return render(request, 'intro/message_form.html', context)

def update(request, pk):

    message = get_object_or_404(Message, pk=pk)

    form = MessageCreateForm(request.POST or None, instance = message)

    if request.method =='POST' and form.is_valid():
        form.save()
        return redirect('intro:_list')
    context = {
        'form':form
    }
    return render(request, 'intro/message_form.html', context)

def delete(request, pk):
    message = get_object_or_404(Message, pk=pk)

    if request.method =='POST':
        message.delete()
        return redirect('intro:_list')

    context = {
        'message':message,
    }
    return render(request, 'intro/message_confirm_delete.html', context)

def detail(request, pk):
    message = get_object_or_404(Message, pk=pk)

    context ={
        'message':message
    }

    return render(request, 'intro/message_detail.html', context)

django/webapp/intro/templates/intro/base.html
{% load static %}
<!doctype html>
<html lang="ja">
  <head>
    <title>Introduction</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel = "stylesheet" href="{% static 'css/main.css' %}">

  </head>
  <body class = "main" style = "background:#EDFFBE">
    <div class = "container">

        <nav class="navbar navbar-expand-sm navbar-dark bg-dark mt-3 mb-3">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'intro:index' %}">ホームページ</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'intro:add' %}">メッセージページ</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'intro:_list' %}">メッセージ一覧</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            チームメンバ
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'intro:masaru' %}">藤牧優</a>
                            <a class="dropdown-item" href="{% url 'intro:yuka' %}">藤本優花</a>
                            <a class="dropdown-item" href="{% url 'intro:masaki' %}">板谷将貴</a>
                            <a class="dropdown-item" href="{% url 'intro:makiyama' %}">牧山秀文</a>
                        </div>
                    </li>
                </ul>
                </div>
        </nav>
    
      {% block content %}
      {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% block extrajs %}{% endblock %}
  </body>
</html>

django/webapp/intro/templates/intro/home.html
{% extends 'intro/base.html' %}
{% load static %}

{% block content %}

<div style = "background:radial-gradient(red, yellow)">
<h1 style = "color:black">TEAM 05 - 01 </h1>

<figure class="masaru" style = "float:left; padding: 20px; ">
   <a href="{% url 'intro:masaru' %}"><img src="/static/masaru_04.jpg" alt="Masaru Fujimaki" width="320" height="240"></a>
    <figcaption>Masaru Fujimaki</figcaption>
</figure>
    
<figure class="yuka"  style = "float:left; padding: 20px; ">
    <a href="{% url 'intro:yuka' %}"><img src="/static/yuka_04.jpg" alt="Yuka Fujimoto" width="320" height="240"></a>
    <figcaption>Yuka Fujimoto</figcaption>
</figure>

<figure class="masaki" style = "float:left; padding: 20px;">
    <a href="{% url 'intro:masaki' %}"><img src="/static/masaki_04.jpg" alt="Masaki Itaya" width="320" height="240"></a>
        <figcaption>Itaya Masaki</figcaption>
</figure>

<figure class="makiyama" style = "float:left; padding: 20px;">
    <a href="{% url 'intro:makiyama' %}"><img src="/static/makiyama_02.jpg" alt="Makiyama Hidefumi" width="320" height="240"></a>
        <figcaption>Hidefumi Makiyama</figcaption>
 </figure>

{% endblock %}

django/webapp/intro/templates/intro/makiyama.html
{% extends 'intro/base.html' %}
{% load static %}
<link rel = "stylesheet" href="{% static 'css/styles.css' %}">

{% block content %}

<div style = "background:radial-gradient(red, yellow)">
<h1 style = "color:black">Makiyama, Hidefumi : AS-FS </h1>
<div id="carouselFadeExampleIndicators" class="carousel slide carousel-fade" data-ride="carousel">
    <div class="carousel-inner" role="listbox">
      <div class="carousel-item active">
        <img class="d-block w-100" src="/static/makiyama_01.jpg" >
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="/static/makiyama_02.jpg" >
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="/static/makiyama_03.jpg" >
      </div>
    </div>
   <a class="carousel-control-prev" href="#carouselFadeExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselFadeExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

<div class = "introduction" style = "border:dashed;">
    <h2>自己紹介</h2>
    <p>人生最大のチャレンジは三年半ほど塾の経営をしたことでした。</p>
    <br>
    <p>また、人生最長の習慣は、自己研鑽の一貫としてカラオケに週一のペースで通っていることです。人生最高の体験はカナダのヴィクトリアへの三回ほどの計半年にわたる短期留学でした</p>
</div>

{% endblock %}

django/webapp/intro/templates/intro/masaki.html
{% extends 'intro/base.html' %}


{% block content %}

<div style = "background:radial-gradient(red, yellow)">
<h1 style = "color:black">Masaki, Itaya : AS-FS </h1>
<div id="carouselFadeExampleIndicators" class="carousel slide carousel-fade" data-ride="carousel">
    <div class="carousel-inner" role="listbox">
      <div class="carousel-item active">
        <img class="d-block w-100" src="/static/masaki_01.jpg" >
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="/static/masaki_02.jpg" >
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="/static/masaki_03.png" >
      </div>
    </div>
   <a class="carousel-control-prev" href="#carouselFadeExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselFadeExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

<div class = "introduction" style = "border:dashed;">
    <h2>自己紹介</h2>
    <p>AS-FS所属の板谷将貴です。</p>
    <br>
    <p>趣味はギター、麻雀、パチンコ、スロットです。</p>
</div>
{% endblock %}

django/webapp/intro/templates/intro/masaru.html
{% extends 'intro/base.html' %}
{% load static %}
<link rel = "stylesheet" href="{% static 'css/styles.css' %}">

{% block content %}

<div style = "background:radial-gradient(red, yellow)">
<h1 style = "color:black">Masaru, Fujimaki : AS-FS </h1>
<div id="carouselFadeExampleIndicators" class="carousel slide carousel-fade" data-ride="carousel">
    <div class="carousel-inner" role="listbox">
      <div class="carousel-item active">
        <img class="d-block w-100" src="/static/masaru_01.jpg" >
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="/static/masaru_02.jpg" >
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="/static/masaru_03.png" >
      </div>
    </div>
   <a class="carousel-control-prev" href="#carouselFadeExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselFadeExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

<div class = "introduction" style = "border:dashed;">
    <h2>自己紹介</h2>
    <br>
    <p>アメリカにテニスでスポーツ留学し、テニスチームのキャプテンを勤めていました。</p>
    <p>7際の頃に中国の上海へ、18歳の頃にアメリカのロチェスターへ、22歳で日本へ本帰国。</p>
</div>

{% endblock %}

django/webapp/intro/templates/intro/message_confirm_delete.html
{% extends 'intro/base.html' %}

{% block content %}
<form action ="" method = "POST">
    <table class = "table">
        <tr>
            <th>タイトル</th>
            <td>{{ message.title }}</td>
        </tr>
        <tr>
            <th>メッセージ</th>
            <td>{{ message.text }}</td>
        </tr>
        <tr>
            <th>日付</th>
            <td>{{ message.date }}</td>
        </tr>
    </table>
    <p>こちらのメッセージを削除します。</p>
    <button type = "submit" class = "btn btn-primary">削除</button>
    {% csrf_token %}
</form>
{% endblock %}

django/webapp/intro/templates/intro/message_detail.html
{% extends 'intro/base.html' %}

{% block content %}

    <table class = "table">
        <tr>
            <th>宛先</th>
            <td>{{ message.title }}</td>
        </tr>
        <tr>
            <th>メッセージ</th>
            <td>{{ message.text }}</td>
        </tr>
        <tr>
            <th>日付</th>
            <td>{{ message.date }}</td>
        </tr>
    </table>
{% endblock %}

django/webapp/intro/templates/intro/message_form.html
{% extends 'intro/base.html' %}

{% block content %}
<p>{{ message.title }}</p>
<form action = "" method = "POST">
    <table class = "table">
        <tr>
            <th>宛先</th>
            <td>{{ form.title }}</td>
        </tr>
        <tr>
            <th>メッセージ</th>
            <td>{{ form.text }}</td>
        </tr>
        <tr>
            <th>日付</th>
            <td>{{ form.date }}</td>
        </tr>
    </table>

    <button type = "submit" class = "btn btn-primary">送信</button>
    {% csrf_token %}
</form>
{% endblock %}

django/webapp/intro/templates/intro/message_list.html
{% extends 'intro/base.html' %}

{% block content %}
<h1>メッセージ一覧</h1>
<table class = "table">
    <thead style = background-color:#B22222>
        <tr>
            <th>宛先</th>
            <th>日付</th>
            <th>更新</th>
            <th>削除</th>
        </tr>
    </thead>
    <tbody>
            {% for message in message_list %}
            <tr>
                <td><a href = "{% url 'intro:detail' message.pk %}">{{ message.title }}</a></td>
                <td>{{ message.date }}</td>
                <td><a href="{% url 'intro:update' message.pk %}">更新</a></td>
                <td><a href="{% url 'intro:delete' message.pk %}">削除</a></td>
            </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock %}

django/webapp/intro/templates/intro/question.html
{% extends 'intro/base.html' %}

{% block content %}
<h1>メッセージ</h1>
{% endblock %}

django/webapp/intro/templates/intro/yuka.html
{% extends 'intro/base.html' %}


{% block content %}

<div style = "background:radial-gradient(red, yellow)">
<h1 style = "color:black">Yuka, Fujimoto : AS-FS </h1>
<div id="carouselFadeExampleIndicators" class="carousel slide carousel-fade" data-ride="carousel">
    <div class="carousel-inner" role="listbox">
      <div class="carousel-item active">
        <img class="d-block w-100" src="/static/yuka_01.jpg" >
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="/static/yuka_02.jpg" >
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="/static/yuka_03.jpg" >
      </div>
    </div>
   <a class="carousel-control-prev" href="#carouselFadeExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselFadeExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

<div class = "introduction" style = "border:dashed;">
    <h2>自己紹介</h2>
    <p>大学時代はLockダンスに打ち込んでいました。</p>
    <br>
    <p>食べ飲み大好きです。量食べます。わんこそば100杯チャレンジ成功しました！！！</p>
</div>
{% endblock %}